### ISSUE TITLE
Small Fix for the buttons on light mode 

### ISSUE THREAD

**Issue by bgraver** [neilpl24/pierreanalyticsource#58]
I tried making a PR but I don't have permission (which is fair). Can you update the text color for light mode to be black regardless of the background color?
<img width="928" alt="image" src="https://github.com/user-attachments/assets/ed0f2901-2c23-4809-98c6-b5a1dcb1b9f4">

Thanks!

**Comment by bsummy** [comment]
Oh! Hello there! 
 
This one is my fault - Neil added the dark mode a bit ago, and I forgot to validate in both styles. I'll have Neil allow your PRs and we can take a look at merging your code.

**Comment by neilpl24** [comment]
Hey @bgraver ! Did you try forking the repo and then making the PR? That should work. Tysm for creating the issue!

**Comment by neilpl24** [comment]
Thank you @bgraver! You are now on the release notes and your changes are live.
